Repository May-I-AI-Integrated-Platform/BE, pull requests merged in 2025-04, with the labels that each got.

#9 [FEAT] #7 채팅 방 추가 기능 구현
  build.gradle
  src/main/java/ai/Mayi/apiPayload/code/status/ErrorStatus.java
  src/main/java/ai/Mayi/apiPayload/exception/handler/ChatHandler.java
  src/main/java/ai/Mayi/converter/ChatConverter.java
  src/main/java/ai/Mayi/domain/Chat.java
  src/main/java/ai/Mayi/repository/ChatRepository.java
  src/main/java/ai/Mayi/service/ChatService.java
  src/main/java/ai/Mayi/web/controller/ChatController.java
  src/main/java/ai/Mayi/web/dto/ChatDTO.java
Labels: :sparkles: feature

#12 [FEAT] #10 토큰 조회 기능 구현
  src/main/java/ai/Mayi/apiPayload/code/status/ErrorStatus.java
  src/main/java/ai/Mayi/apiPayload/exception/handler/TokenHandler.java
  src/main/java/ai/Mayi/repository/TokenRepository.java
  src/main/java/ai/Mayi/service/TokenService.java
  src/main/java/ai/Mayi/web/controller/TokenController.java
  src/main/java/ai/Mayi/web/dto/TokenDTO.java
Labels: :sparkles: feature

#13 [FEAT] #11 채팅 목록 조회 기능
  src/main/java/ai/Mayi/converter/ChatConverter.java
  src/main/java/ai/Mayi/repository/ChatRepository.java
  src/main/java/ai/Mayi/service/ChatService.java
  src/main/java/ai/Mayi/web/controller/ChatController.java
  src/main/java/ai/Mayi/web/dto/ChatDTO.java
Labels: :sparkles: feature

#17 [FEAT] #16 채팅 컨트롤러 비동기 구현
  src/main/java/ai/Mayi/MayiApplication.java
  src/main/java/ai/Mayi/apiPayload/code/status/ErrorStatus.java
  src/main/java/ai/Mayi/service/MessageService.java
  src/main/java/ai/Mayi/web/controller/MessageController.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#20 [FEAT] #18 Bard 연동
  build.gradle
  src/main/java/ai/Mayi/apiPayload/code/status/ErrorStatus.java
  src/main/java/ai/Mayi/service/MessageService.java
  src/main/java/ai/Mayi/web/dto/MessageDTO.java
Labels: :sparkles: feature

#21 [FEAT] #19 GPT API 연동
  src/main/java/ai/Mayi/apiPayload/code/status/ErrorStatus.java
  src/main/java/ai/Mayi/config/AIConfig.java
  src/main/java/ai/Mayi/repository/TokenRepository.java
  src/main/java/ai/Mayi/service/MessageService.java
  src/main/java/ai/Mayi/web/controller/ChatController.java
  src/main/java/ai/Mayi/web/dto/MessageDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#24 [FEAT] #23 DeepSeek 연동
  src/main/java/ai/Mayi/apiPayload/code/status/ErrorStatus.java
  src/main/java/ai/Mayi/domain/enums/MessageType.java
  src/main/java/ai/Mayi/domain/enums/TokenType.java
  src/main/java/ai/Mayi/service/MessageService.java
  src/main/java/ai/Mayi/service/TokenService.java
  src/main/java/ai/Mayi/web/controller/MessageController.java
  src/main/java/ai/Mayi/web/dto/MessageDTO.java
Labels: :sparkles: feature

#26 [FEAT] #22 Claude 연동
  src/main/java/ai/Mayi/apiPayload/code/status/ErrorStatus.java
  src/main/java/ai/Mayi/config/AIConfig.java
  src/main/java/ai/Mayi/service/MessageService.java
  src/main/java/ai/Mayi/web/controller/MessageController.java
  src/main/java/ai/Mayi/web/dto/MessageDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#28 [REFACTOR] #27 GPT WebClient 방식 수정
  src/main/java/ai/Mayi/config/AIConfig.java
  src/main/java/ai/Mayi/service/MessageService.java
Labels: :recycle: refactor

#31 [FEAT] #3 일반 로그인 기능 구현
  src/main/java/ai/Mayi/apiPayload/code/status/ErrorStatus.java
  src/main/java/ai/Mayi/apiPayload/exception/handler/JwtHandler.java
  src/main/java/ai/Mayi/apiPayload/exception/handler/UserHandler.java
  src/main/java/ai/Mayi/config/SecurityConfig.java
  src/main/java/ai/Mayi/domain/User.java
  src/main/java/ai/Mayi/jwt/CookieUtil.java
  src/main/java/ai/Mayi/jwt/JwtAuthenticationFilter.java
  src/main/java/ai/Mayi/jwt/JwtUtil.java
  src/main/java/ai/Mayi/service/JwtUtil.java
  src/main/java/ai/Mayi/service/MyUserDetailsService.java
  src/main/java/ai/Mayi/service/UserServiceImpl.java
  src/main/java/ai/Mayi/web/controller/UserController.java
  src/main/java/ai/Mayi/web/dto/JwtTokenDTO.java
  src/main/java/ai/Mayi/web/dto/UserDTO.java
  src/test/java/ai/Mayi/domain/UserSaveTest.java
Labels: :sparkles: feature

#34 [FEAT] #32 유저 정보 목록 API 기능 구현
  src/main/java/ai/Mayi/apiPayload/exception/handler/GlobalExceptionHandler.java
  src/main/java/ai/Mayi/jwt/JwtAuthenticationFilter.java
  src/main/java/ai/Mayi/jwt/JwtUtil.java
  src/main/java/ai/Mayi/service/UserServiceImpl.java
  src/main/java/ai/Mayi/web/controller/UserController.java
  src/main/java/ai/Mayi/web/dto/UserDTO.java
Labels: :sparkles: feature

#36 [FEAT] #33 Docker 설정
  Dockerfile
  build.gradle
Labels: :sparkles: feature, :pick: ci

#37 [FEAT] #35 구글 소셜로그인 구현
  build.gradle
  src/main/java/ai/Mayi/apiPayload/code/status/ErrorStatus.java
  src/main/java/ai/Mayi/config/SecurityConfig.java
  src/main/java/ai/Mayi/domain/User.java
  src/main/java/ai/Mayi/jwt/CookieUtil.java
  src/main/java/ai/Mayi/jwt/JwtAuthenticationFilter.java
  src/main/java/ai/Mayi/oauth/CustomOAuth2SuccessHandler.java
  src/main/java/ai/Mayi/oauth/CustomOAuth2User.java
  src/main/java/ai/Mayi/oauth/CustomOAuth2UserService.java
  src/main/java/ai/Mayi/oauth/OAuth2Properties.java
  src/main/java/ai/Mayi/oauth/OAuthUserHelper.java
  src/main/java/ai/Mayi/service/UserServiceImpl.java
  src/main/java/ai/Mayi/web/dto/UserDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#40 [FEAT] #39 메세지 구현
  src/main/java/ai/Mayi/service/MessageService.java
  src/main/java/ai/Mayi/service/UserServiceImpl.java
  src/main/java/ai/Mayi/web/controller/MessageController.java
  src/main/java/ai/Mayi/web/dto/MessageDTO.java
Labels: :sparkles: feature

#42 [FEAT] #38 카카오 소셜로그인 기능 구현
  src/main/java/ai/Mayi/apiPayload/code/status/ErrorStatus.java
  src/main/java/ai/Mayi/apiPayload/exception/handler/SocialLoginHandler.java
  src/main/java/ai/Mayi/config/SecurityConfig.java
  src/main/java/ai/Mayi/oauth/CustomOAuth2SuccessHandler.java
  src/main/java/ai/Mayi/oauth/CustomOAuth2UserService.java
  src/main/java/ai/Mayi/oauth/GoogleUserInfo.java
  src/main/java/ai/Mayi/oauth/KakaoUserInfo.java
  src/main/java/ai/Mayi/oauth/OAuth2RegistrationIdFilter.java
  src/main/java/ai/Mayi/oauth/OAuth2UserInfo.java
  src/main/java/ai/Mayi/oauth/OAuthUserHelper.java
  src/main/resources/application.yml
Labels: :bug: bugfix, :sparkles: feature

#43 [FEAT] #41 각 api 유저 조회 방식 변경
  src/main/java/ai/Mayi/service/ChatService.java
  src/main/java/ai/Mayi/service/TokenService.java
  src/main/java/ai/Mayi/service/UserServiceImpl.java
  src/main/java/ai/Mayi/web/controller/ChatController.java
  src/main/java/ai/Mayi/web/controller/MessageController.java
  src/main/java/ai/Mayi/web/controller/TokenController.java
  src/main/java/ai/Mayi/web/dto/ChatDTO.java
  src/main/java/ai/Mayi/web/dto/MessageDTO.java
  src/main/java/ai/Mayi/web/dto/TokenDTO.java
Labels: :sparkles: feature

#45 [FEAT] #44 네이버 소셜로그인 기능 구현
  src/main/java/ai/Mayi/oauth/CustomOAuth2SuccessHandler.java
  src/main/java/ai/Mayi/oauth/CustomOAuth2UserService.java
  src/main/java/ai/Mayi/oauth/NaverUserInfo.java
  src/main/resources/application.yml
Labels: :sparkles: feature

#47 [REFACTOR] #46 소셜 로그인 및 JWT 관련 리팩토링
  src/main/java/ai/Mayi/jwt/CookieUtil.java
  src/main/java/ai/Mayi/jwt/JwtAuthenticationFilter.java
  src/main/java/ai/Mayi/jwt/JwtUtil.java
  src/main/java/ai/Mayi/oauth/CustomOAuth2SuccessHandler.java
  src/main/java/ai/Mayi/oauth/CustomOAuth2User.java
  src/main/java/ai/Mayi/oauth/CustomOAuth2UserService.java
  src/main/java/ai/Mayi/oauth/OAuth2RegistrationIdFilter.java
Labels: :recycle: refactor

#50 [FEAT] #49 채팅방 삭제 기능 구현
  src/main/java/ai/Mayi/service/ChatService.java
  src/main/java/ai/Mayi/web/controller/ChatController.java
Labels: :sparkles: feature

#53 [FEAT] 쿠키 구조 변경 및 쿠키 삭제 메서드 기능 추가
  src/main/java/ai/Mayi/jwt/CookieUtil.java
  src/main/java/ai/Mayi/service/UserServiceImpl.java
Labels: :sparkles: feature, :recycle: refactor
